package projectorapp;

import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 * ConfigurationWindow
 * 
 * @author marzin
 * @version 0.1
 */

public class ConfigurationWindow extends javax.swing.JFrame
{
    /**
     * Creates new form NewJFrame
     */
    
    public ConfigurationWindow() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type_Group = new javax.swing.ButtonGroup();
        connection_Group = new javax.swing.ButtonGroup();
        n_Group = new javax.swing.ButtonGroup();
        info_Panel = new javax.swing.JPanel();
        info_Label = new javax.swing.JLabel();
        name_Label = new javax.swing.JLabel();
        name_TextField = new javax.swing.JTextField();
        type_Label = new javax.swing.JLabel();
        type_Button1 = new javax.swing.JRadioButton();
        type_Button2 = new javax.swing.JRadioButton();
        make_Label = new javax.swing.JLabel();
        make_ComboBox = new javax.swing.JComboBox();
        model_Label = new javax.swing.JLabel();
        model_ComboBox = new javax.swing.JComboBox();
        settings_Label = new javax.swing.JLabel();
        ip_TextField1 = new javax.swing.JTextField();
        ip_TextField2 = new javax.swing.JTextField();
        ip_TextField3 = new javax.swing.JTextField();
        ip_TextField4 = new javax.swing.JTextField();
        dot_Label1 = new javax.swing.JLabel();
        dot_Label2 = new javax.swing.JLabel();
        dot_Label3 = new javax.swing.JLabel();
        or_Label = new javax.swing.JLabel();
        speed_ComboBox = new javax.swing.JComboBox();
        dataBits_ComboBox = new javax.swing.JComboBox();
        parity_ComboBox = new javax.swing.JComboBox();
        stopBits_ComboBox = new javax.swing.JComboBox();
        connection_Button1 = new javax.swing.JRadioButton();
        connection_Button2 = new javax.swing.JRadioButton();
        tec_Label = new javax.swing.JLabel();
        tec_CheckBox = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        connection_Label = new javax.swing.JLabel();
        pc_CheckBox = new javax.swing.JCheckBox();
        laptop_CheckBox = new javax.swing.JCheckBox();
        dvd_CheckBox = new javax.swing.JCheckBox();
        vcr_CheckBox = new javax.swing.JCheckBox();
        doccam_CheckBox = new javax.swing.JCheckBox();
        pc_ComboBox = new javax.swing.JComboBox();
        laptop_ComboBox = new javax.swing.JComboBox();
        dvd_ComboBox = new javax.swing.JComboBox();
        vcr_ComboBox = new javax.swing.JComboBox();
        doccam_ComboBox = new javax.swing.JComboBox();
        button_Panel = new javax.swing.JPanel();
        cancel_Button = new javax.swing.JButton();
        run_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuration Editor");

        info_Label.setText("Details:");

        name_Label.setText("Name:");

        type_Label.setText("Type:");

        type_Group.add(type_Button1);
        type_Button1.setText("Projector");

        type_Group.add(type_Button2);
        type_Button2.setText("Television");

        make_Label.setText("Make:");

        make_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(projectorapp.ProjectorTypes.getMakes("Projector")));
        make_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                make_ComboBoxActionPerformed(evt);
            }
        });

        model_Label.setText("Model:");

        model_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model_ComboBoxActionPerformed(evt);
            }
        });

        settings_Label.setText("Connection Settings:");

        ip_TextField1.setText("xxx");

        ip_TextField2.setText("xxx");

        ip_TextField3.setText("xxx");

        ip_TextField4.setText("xxx");

        dot_Label1.setText(".");

        dot_Label2.setText(".");

        dot_Label3.setText(".");

        or_Label.setText("or");

        speed_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(projectorapp.Serial.getSpeeds()));

        dataBits_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(projectorapp.Serial.getDataBits()));

        parity_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(projectorapp.Serial.getParity()));

        stopBits_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(projectorapp.Serial.getStopBits()));

        connection_Group.add(connection_Button1);
        connection_Button1.setSelected(true);
        connection_Button1.setText("IP Address:");
        connection_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connection_Button1ActionPerformed(evt);
            }
        });

        connection_Group.add(connection_Button2);
        connection_Button2.setText("Serial:");
        connection_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connection_Button2ActionPerformed(evt);
            }
        });

        tec_Label.setText("TEC Classroom:");

        tec_CheckBox.setText(" ");

        org.jdesktop.layout.GroupLayout info_PanelLayout = new org.jdesktop.layout.GroupLayout(info_Panel);
        info_Panel.setLayout(info_PanelLayout);
        info_PanelLayout.setHorizontalGroup(
            info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(info_PanelLayout.createSequentialGroup()
                .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(info_PanelLayout.createSequentialGroup()
                        .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(info_PanelLayout.createSequentialGroup()
                                .add(112, 112, 112)
                                .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(or_Label)
                                    .add(info_PanelLayout.createSequentialGroup()
                                        .add(ip_TextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(dot_Label1)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(ip_TextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(dot_Label2)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ip_TextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(dot_Label3))
                            .add(info_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(info_Label)
                                    .add(info_PanelLayout.createSequentialGroup()
                                        .add(6, 6, 6)
                                        .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                .add(info_PanelLayout.createSequentialGroup()
                                                    .add(model_Label)
                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                    .add(model_ComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .add(info_PanelLayout.createSequentialGroup()
                                                    .add(type_Label)
                                                    .add(18, 18, 18)
                                                    .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(type_Button2)
                                                        .add(type_Button1)))
                                                .add(info_PanelLayout.createSequentialGroup()
                                                    .add(make_Label)
                                                    .add(18, 18, 18)
                                                    .add(make_ComboBox, 0, 124, Short.MAX_VALUE)))
                                            .add(settings_Label)
                                            .add(connection_Button1)
                                            .add(connection_Button2)
                                            .add(info_PanelLayout.createSequentialGroup()
                                                .add(name_Label)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(name_TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(info_PanelLayout.createSequentialGroup()
                                                .add(tec_Label)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(tec_CheckBox)))))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ip_TextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(info_PanelLayout.createSequentialGroup()
                        .add(86, 86, 86)
                        .add(speed_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dataBits_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(parity_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(stopBits_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        info_PanelLayout.setVerticalGroup(
            info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, info_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(info_Label)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(name_Label)
                    .add(name_TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(type_Label)
                    .add(type_Button1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(type_Button2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(make_Label)
                    .add(make_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(model_Label)
                    .add(model_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(settings_Label)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ip_TextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dot_Label1)
                    .add(ip_TextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dot_Label2)
                    .add(ip_TextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ip_TextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dot_Label3)
                    .add(connection_Button1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(or_Label)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(connection_Button2)
                    .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(speed_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(dataBits_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(parity_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(stopBits_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(info_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tec_Label)
                    .add(tec_CheckBox))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        //Disable the Serial ComboBox's
        speed_ComboBox.setEnabled(false);
        dataBits_ComboBox.setEnabled(false);
        parity_ComboBox.setEnabled(false);
        stopBits_ComboBox.setEnabled(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        connection_Label.setText("Connection Info:");

        pc_CheckBox.setSelected(true);
        pc_CheckBox.setText("PC");
        pc_CheckBox.setEnabled(false);

        laptop_CheckBox.setSelected(true);
        laptop_CheckBox.setText("Laptop");
        laptop_CheckBox.setEnabled(false);

        dvd_CheckBox.setText("DVD Player");
        dvd_CheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dvd_CheckBoxItemStateChanged(evt);
            }
        });

        vcr_CheckBox.setText("VCR");
        vcr_CheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vcr_CheckBoxItemStateChanged(evt);
            }
        });

        doccam_CheckBox.setText("Document Camera");
        doccam_CheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                doccam_CheckBoxItemStateChanged(evt);
            }
        });

        pc_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        laptop_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dvd_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        vcr_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        doccam_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancel_Button.setText("Cancel");
        cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_ButtonActionPerformed(evt);
            }
        });

        run_Button.setText("RUN!!");
        run_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_ButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout button_PanelLayout = new org.jdesktop.layout.GroupLayout(button_Panel);
        button_Panel.setLayout(button_PanelLayout);
        button_PanelLayout.setHorizontalGroup(
            button_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(button_PanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(cancel_Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(run_Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        button_PanelLayout.setVerticalGroup(
            button_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(button_PanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(button_PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(run_Button)
                    .add(cancel_Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(connection_Label)
                .add(0, 0, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(doccam_CheckBox)
                    .add(vcr_CheckBox)
                    .add(dvd_CheckBox)
                    .add(pc_CheckBox)
                    .add(laptop_CheckBox))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(laptop_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pc_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dvd_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(vcr_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(doccam_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(button_Panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(connection_Label)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pc_CheckBox)
                    .add(pc_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(laptop_CheckBox)
                    .add(laptop_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dvd_CheckBox)
                    .add(dvd_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(vcr_CheckBox)
                    .add(vcr_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(doccam_CheckBox)
                    .add(doccam_ComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(button_Panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dvd_ComboBox.setEnabled(false);
        vcr_ComboBox.setEnabled(false);
        doccam_ComboBox.setEnabled(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(info_Panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSeparator1)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(info_Panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connection_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connection_Button1ActionPerformed
        //Disable the Serial ComboBox's
        speed_ComboBox.setEnabled(false);
        dataBits_ComboBox.setEnabled(false);
        parity_ComboBox.setEnabled(false);
        stopBits_ComboBox.setEnabled(false);
        //Enable the IP TextFields
        ip_TextField1.setEnabled(true);
        ip_TextField1.setEditable(true);
        ip_TextField2.setEnabled(true);
        ip_TextField2.setEditable(true);
        ip_TextField3.setEnabled(true);
        ip_TextField3.setEditable(true);
        ip_TextField4.setEnabled(true);
        ip_TextField4.setEditable(true);
    }//GEN-LAST:event_connection_Button1ActionPerformed

    private void connection_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connection_Button2ActionPerformed
        //Disable the IP TextFields
        ip_TextField1.setEnabled(false);
        ip_TextField1.setEditable(false);
        ip_TextField2.setEnabled(false);
        ip_TextField2.setEditable(false);
        ip_TextField3.setEnabled(false);
        ip_TextField3.setEditable(false);
        ip_TextField4.setEnabled(false);
        ip_TextField4.setEditable(false);
        //Enable the Serial ComboBox's
        speed_ComboBox.setEnabled(true);
        dataBits_ComboBox.setEnabled(true);
        parity_ComboBox.setEnabled(true);
        stopBits_ComboBox.setEnabled(true);
    }//GEN-LAST:event_connection_Button2ActionPerformed

    private void cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_ButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancel_ButtonActionPerformed

    private void run_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_run_ButtonActionPerformed

    private void dvd_CheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dvd_CheckBoxItemStateChanged
        // Enable the jComboBox when the jCheckBox is selected
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            dvd_ComboBox.setEnabled(true);
        }
        // Disable the jComboBox when the jCheckBox is deselected
        else if(evt.getStateChange() == ItemEvent.DESELECTED)
        {
            dvd_ComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_dvd_CheckBoxItemStateChanged

    private void vcr_CheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vcr_CheckBoxItemStateChanged
        // Enable the jComboBox when the jCheckBox is selected
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            vcr_ComboBox.setEnabled(true);
        }
        // Disable the jComboBox when the jCheckBox is deselected
        else if(evt.getStateChange() == ItemEvent.DESELECTED)
        {
            vcr_ComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_vcr_CheckBoxItemStateChanged

    private void doccam_CheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_doccam_CheckBoxItemStateChanged
        // Enable the jComboBox when the jCheckBox is selected
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            doccam_ComboBox.setEnabled(true);
        }
        // Disable the jComboBox when the jCheckBox is deselected
        else if(evt.getStateChange() == ItemEvent.DESELECTED)
        {
            doccam_ComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_doccam_CheckBoxItemStateChanged

    private void make_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_make_ComboBoxActionPerformed
        // TODO add your handling code here:
        String[] models;
        JComboBox cb = (JComboBox)evt.getSource();
        String make = (String)cb.getSelectedItem();
        //System.out.println("Make: " + make);
        models = ProjectorTypes.getModels(make);
        model_ComboBox.setModel(new DefaultComboBoxModel(models));
    }//GEN-LAST:event_make_ComboBoxActionPerformed

    private void model_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_model_ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigurationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigurationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigurationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigurationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigurationWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel button_Panel;
    private javax.swing.JButton cancel_Button;
    private javax.swing.JRadioButton connection_Button1;
    private javax.swing.JRadioButton connection_Button2;
    private javax.swing.ButtonGroup connection_Group;
    private javax.swing.JLabel connection_Label;
    private javax.swing.JComboBox dataBits_ComboBox;
    private javax.swing.JCheckBox doccam_CheckBox;
    private javax.swing.JComboBox doccam_ComboBox;
    private javax.swing.JLabel dot_Label1;
    private javax.swing.JLabel dot_Label2;
    private javax.swing.JLabel dot_Label3;
    private javax.swing.JCheckBox dvd_CheckBox;
    private javax.swing.JComboBox dvd_ComboBox;
    private javax.swing.JLabel info_Label;
    private javax.swing.JPanel info_Panel;
    private javax.swing.JTextField ip_TextField1;
    private javax.swing.JTextField ip_TextField2;
    private javax.swing.JTextField ip_TextField3;
    private javax.swing.JTextField ip_TextField4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox laptop_CheckBox;
    private javax.swing.JComboBox laptop_ComboBox;
    private javax.swing.JComboBox make_ComboBox;
    private javax.swing.JLabel make_Label;
    private javax.swing.JComboBox model_ComboBox;
    private javax.swing.JLabel model_Label;
    private javax.swing.ButtonGroup n_Group;
    private javax.swing.JLabel name_Label;
    private javax.swing.JTextField name_TextField;
    private javax.swing.JLabel or_Label;
    private javax.swing.JComboBox parity_ComboBox;
    private javax.swing.JCheckBox pc_CheckBox;
    private javax.swing.JComboBox pc_ComboBox;
    private javax.swing.JButton run_Button;
    private javax.swing.JLabel settings_Label;
    private javax.swing.JComboBox speed_ComboBox;
    private javax.swing.JComboBox stopBits_ComboBox;
    private javax.swing.JCheckBox tec_CheckBox;
    private javax.swing.JLabel tec_Label;
    private javax.swing.JRadioButton type_Button1;
    private javax.swing.JRadioButton type_Button2;
    private javax.swing.ButtonGroup type_Group;
    private javax.swing.JLabel type_Label;
    private javax.swing.JCheckBox vcr_CheckBox;
    private javax.swing.JComboBox vcr_ComboBox;
    // End of variables declaration//GEN-END:variables
}